/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package uk.co.jofaircloth.dovesguide;

public final class R {
    public static final class array {
        public static final int no_bells=0x7f050000;
        public static final int practice_night=0x7f050001;
        public static final int sort_order_text=0x7f050002;
        public static final int sort_order_values=0x7f050003;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int padding_large=0x7f060002;
        public static final int padding_medium=0x7f060001;
        public static final int padding_small=0x7f060000;
    }
    public static final class drawable {
        public static final int bell2=0x7f020000;
        public static final int ic_action_search=0x7f020001;
        public static final int ic_chevron=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int ic_position=0x7f020004;
    }
    public static final class id {
        public static final int about_build_database_button=0x7f0a0000;
        public static final int about_content=0x7f0a0001;
        public static final int browse_distance_text=0x7f0a0007;
        public static final int browse_no_bells_text=0x7f0a0005;
        public static final int browse_practice_night_text=0x7f0a0004;
        public static final int browse_tower_text=0x7f0a0003;
        public static final int browse_weight_text=0x7f0a0006;
        public static final int details_additional_location_layout=0x7f0a000e;
        public static final int details_additional_location_text=0x7f0a000f;
        public static final int details_affiliation_text=0x7f0a0014;
        public static final int details_aka=0x7f0a0015;
        public static final int details_contractor_and_date_text=0x7f0a0021;
        public static final int details_county_country_text=0x7f0a0010;
        public static final int details_date_tuned_text=0x7f0a0022;
        public static final int details_diocese_text=0x7f0a0013;
        public static final int details_extra_info_text=0x7f0a001d;
        public static final int details_grid_ref_text=0x7f0a0012;
        public static final int details_ground_floor_text=0x7f0a001b;
        public static final int details_key_text=0x7f0a0018;
        public static final int details_layout_root=0x7f0a0008;
        public static final int details_location_image=0x7f0a000a;
        public static final int details_location_satnav_image=0x7f0a000d;
        public static final int details_no_bells_text=0x7f0a0016;
        public static final int details_position=0x7f0a0009;
        public static final int details_postcode_text=0x7f0a0011;
        public static final int details_practice_night_text=0x7f0a0019;
        public static final int details_practice_time_text=0x7f0a001a;
        public static final int details_prxf_text=0x7f0a001e;
        public static final int details_satnav_position=0x7f0a000c;
        public static final int details_satnav_position_layout=0x7f0a000b;
        public static final int details_title=0x7f0a0027;
        public static final int details_toilet_text=0x7f0a001f;
        public static final int details_tower_base_text=0x7f0a0020;
        public static final int details_uringable_text=0x7f0a001c;
        public static final int details_web_text=0x7f0a0023;
        public static final int details_weight_text=0x7f0a0017;
        public static final int item_text=0x7f0a0024;
        public static final int menu_settings=0x7f0a002e;
        public static final int menu_sort=0x7f0a002f;
        public static final int nearby_last_location=0x7f0a0026;
        public static final int nearby_title=0x7f0a0025;
        public static final int pager=0x7f0a0002;
        public static final int search_county_spinner=0x7f0a002b;
        public static final int search_no_bells_spinner=0x7f0a0029;
        public static final int search_practice_night_spinner=0x7f0a002a;
        public static final int search_text=0x7f0a0028;
        public static final int visited_date_picker=0x7f0a002d;
        public static final int visited_notes_text=0x7f0a002c;
    }
    public static final class layout {
        public static final int about_layout=0x7f030000;
        public static final int activity_main=0x7f030001;
        public static final int az_browse_layout=0x7f030002;
        public static final int browse_item_layout=0x7f030003;
        public static final int details_layout=0x7f030004;
        public static final int item_layout=0x7f030005;
        public static final int nearby_layout=0x7f030006;
        public static final int old_details_layout=0x7f030007;
        public static final int search_layout=0x7f030008;
        public static final int visited_layout=0x7f030009;
    }
    public static final class menu {
        public static final int activity_main=0x7f090000;
    }
    public static final class raw {
        public static final int dove=0x7f040000;
    }
    public static final class string {
        public static final int about_content=0x7f070017;
        public static final int additional_location_text=0x7f070016;
        public static final int affiliation_text=0x7f07000e;
        public static final int app_name=0x7f070000;
        public static final int bells_text=0x7f07000f;
        public static final int build_database_text=0x7f07000a;
        public static final int county_text=0x7f070015;
        public static final int details_notes_text=0x7f070012;
        public static final int diocese_text=0x7f07000d;
        public static final int grid_ref_text=0x7f070011;
        public static final int menu_settings=0x7f070007;
        public static final int menu_sort=0x7f070008;
        public static final int no_towers_found=0x7f070014;
        public static final int please_select=0x7f07001c;
        public static final int postcode_text=0x7f070010;
        public static final int practice_details=0x7f070013;
        public static final int search_county_text=0x7f07001b;
        public static final int search_nearby_button_text=0x7f07000b;
        public static final int search_no_bells_text=0x7f070019;
        public static final int search_place_text=0x7f070018;
        public static final int search_practice_night_text=0x7f07001a;
        public static final int string_alt_position_icon=0x7f07000c;
        public static final int title_about=0x7f070001;
        public static final int title_activity_main=0x7f070009;
        public static final int title_browse=0x7f070004;
        public static final int title_details=0x7f070002;
        public static final int title_nearby=0x7f070006;
        public static final int title_results=0x7f070003;
        public static final int title_search=0x7f070005;
        public static final int visited_date=0x7f07001e;
        public static final int visited_notes=0x7f07001d;
    }
    public static final class style {
        public static final int AppTheme=0x7f080000;
        public static final int DescTitle=0x7f080004;
        public static final int DescTitle_FullWidth=0x7f080007;
        public static final int ItemRow=0x7f080003;
        public static final int PopupDialog=0x7f080001;
        public static final int PopupDialogTitle=0x7f080002;
        public static final int Spinner=0x7f080005;
        public static final int bold=0x7f080006;
    }
}
